name: Create release

on:
  push:
    tags: ["**"]

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Create release
        env:
          TAG_NAME: ${{ steps.tag.outputs.TAG }}
          GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
        run: gh release create $TAG_NAME --generate-notes