name: Push Check

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run the Cake script Debug
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          target: Debug
      - name: Run the Cake script Test
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          target: Test
  windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run the Cake script PublishWindows
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          target: PublishWindows
      - name: Run the Cake script PublishWindowsAot
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          target: PublishWindowsAot
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run the Cake script PublishLinux
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          target: PublishLinux
      - name: Run the Cake script PublishLinuxAot
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          target: PublishLinuxAot
