name: Release asset

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

permissions:
  contents: write

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run the Cake script Package
        uses: cake-build/cake-action@v2
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        with:
          cake-version: 4.0.0
          target: Push
      - name: Update release with new asset
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
        run: gh release upload $TAG $ASSET
      - name: Run the Cake script PublishWindows
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          target: PublishWindows
      - name: Update release with new asset
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
        run: |
            gh release upload $TAG $ASSET_win-x64
            gh release upload $TAG $ASSET_win-x86
            gh release upload $TAG $ASSET_win-arm64